In [ ]:
import numpy as np
import pandas as pd
from pathlib import Path


pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 140)

print("Entorno listo ✅")
print("Pandas:", pd.__version__)
print("NumPy :", np.__version__)

Entorno listo ✅
Pandas: 2.2.2
NumPy : 2.0.2

In [ ]:
Path("evaluacion_datos").mkdir(exist_ok=True)

df_crudo_eval = pd.DataFrame({
    "id_estudiante": [201,202,203,204,205,206,207,208,209,210,211,211],
    "nombre": ["Laura","Iván","María","Diego","Sofía","Raúl","Carmen","Joel","Paola","Andrés","Karla","Karla"],
    "edad": [19, 20, np.nan, 22, 21, 19, 20, 23, 21, 20, 22, 22],
    "campus": ["SLP Centro", "slp centro ", "SLP Norte", "SLP Cntro", "Matehuala", "SLP Norte", "Matehuala", "SLP Centro", "SLP Norte", "SLP Centro", "SLP centro", "SLP centro"],
    "modalidad": ["Escolarizada", "escolar", "Mixta", "MIXTA ", "Escolarizada", "Mixta", "Mixta", "Escolarizada", "Escolarizada", "Escolarizada", "Mixta", "Mixta"],
    "promedio": [87, 92, 75, np.nan, 83, 104, 68, 71, 95, 79, 88, 88],
    "asistencia_pct": [93, 86, 80, 88, np.nan, 91, 74, 77, 98, 102, 85, 85],
    "creditos_inscritos": [30, 32, 28, 30, 26, 30, 24, 30, 32, 28, 30, 30],
    "creditos_aprobados": [29, 31, 27, 29, 25, 33, 22, 28, 31, 28, 30, 30]
})

df_apoyos_eval = pd.DataFrame({
    "id_estudiante": [201,203,204,206,208,209,212],
    "beca": ["Sí","No","Sí","No","Sí","No","Sí"],
    "tutoria_horas_mes": [3, 0, 2, 1, 4, 0, 2]
})

df_crudo_eval.to_csv("evaluacion_datos/estudiantes_crudo_eval.csv", index=False)
df_apoyos_eval.to_csv("evaluacion_datos/apoyos_eval.csv", index=False)

print("Archivos creados ✅")
display(df_crudo_eval.head())

Archivos creados ✅

   id_estudiante nombre  edad       campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0   SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro        escolar      92.0            86.0                  32                  31
2            203  María   NaN    SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0    SLP Cntro        MIXTA        NaN            88.0                  30                  29
4            205  Sofía  21.0    Matehuala  Escolarizada      83.0             NaN                  26                  25

actividad a

In [ ]:
#A1
# Importar archivos
df = pd.read_csv("evaluacion_datos/estudiantes_crudo_eval.csv")
apoyos = pd.read_csv("evaluacion_datos/apoyos_eval.csv")

print("Archivos importados correctamente.")

Archivos importados correctamente.

In [ ]:
#A2
print("--- Shape ---")
print(f"Dataset principal: {df.shape}")
print(f"Dataset apoyos: {apoyos.shape}\n")

print("--- Head (df) ---")
display(df.head())

print("\n--- Info (df) ---")
df.info()

print("\n--- Describe (df) ---")
display(df.describe())

--- Shape ---
Dataset principal: (12, 9)
Dataset apoyos: (7, 3)

--- Head (df) ---

   id_estudiante nombre  edad       campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0   SLP Centro  Escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro        escolar      92.0            86.0                  32                  31
2            203  María   NaN    SLP Norte         Mixta      75.0            80.0                  28                  27
3            204  Diego  22.0    SLP Cntro        MIXTA        NaN            88.0                  30                  29
4            205  Sofía  21.0    Matehuala  Escolarizada      83.0             NaN                  26                  25

--- Info (df) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_estudiante       12 non-null     int64
 1   nombre              12 non-null     object
 2   edad                11 non-null     float64
 3   campus              12 non-null     object
 4   modalidad           12 non-null     object
 5   promedio            11 non-null     float64
 6   asistencia_pct      11 non-null     float64
 7   creditos_inscritos  12 non-null     int64
 8   creditos_aprobados  12 non-null     int64
dtypes: float64(3), int64(3), object(3)
memory usage: 996.0+ bytes

--- Describe (df) ---

       id_estudiante       edad    promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
count      12.000000  11.000000   11.000000       11.000000           12.000000           12.000000
mean      206.416667  20.818182   84.545455       87.181818           29.166667           28.583333
std         3.476109   1.328020   10.745824        8.518429            2.329000            2.937480
min       201.000000  19.000000   68.000000       74.000000           24.000000           22.000000
25%       203.750000  20.000000   77.000000       82.500000           28.000000           27.750000
50%       206.500000  21.000000   87.000000       86.000000           30.000000           29.000000
75%       209.250000  22.000000   90.000000       92.000000           30.000000           30.250000
max       211.000000  23.000000  104.000000      102.000000           32.000000           33.000000

actividad b

In [ ]:
# B1
print("Valores faltantes por columna:")
print(df.isna().sum())

Valores faltantes por columna:
id_estudiante         0
nombre                0
edad                  1
campus                0
modalidad             0
promedio              1
asistencia_pct        1
creditos_inscritos    0
creditos_aprobados    0
dtype: int64

In [ ]:
#B2
duplicados = df.duplicated(subset='id_estudiante').sum()
print(f"Registros duplicados por id_estudiante: {duplicados}")

Registros duplicados por id_estudiante: 1

In [ ]:
#B3
print(f"Valores únicos en Campus: {df['campus'].unique()}")
print(f"Valores únicos en Modalidad: {df['modalidad'].unique()}")

Valores únicos en Campus: ['SLP Centro' 'slp centro ' 'SLP Norte' 'SLP Cntro' 'Matehuala'
 'SLP centro']
Valores únicos en Modalidad: ['Escolarizada' 'escolar' 'Mixta' 'MIXTA ']

In [ ]:
#B4 Promedios fuera de 0-100 o Asistencia > 100
fuera_rango_prom = df[(df['promedio'] < 0) | (df['promedio'] > 100)]
fuera_rango_asist = df[df['asistencia_pct'] > 100]

print(f"Registros con promedio fuera de rango (0-100): {len(fuera_rango_prom)}")
print(f"Registros con asistencia > 100%: {len(fuera_rango_asist)}")

Registros con promedio fuera de rango (0-100): 1
Registros con asistencia > 100%: 1

In [ ]:
#B5 Los créditos aprobados no pueden ser mayores a los inscritos
errores_logicos = df[df['creditos_aprobados'] > df['creditos_inscritos']]
print(f"Registros con error lógico (Aprobados > Inscritos): {len(errores_logicos)}")
display(errores_logicos)

Registros con error lógico (Aprobados > Inscritos): 1

   id_estudiante nombre  edad     campus modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
5            206   Raúl  19.0  SLP Norte     Mixta     104.0            91.0                  30                  33

actividad c

In [ ]:
# c1
df_limpio = df.copy()

# 1. Limpieza de texto y normalización
df_limpio['campus'] = df_limpio['campus'].str.strip().str.lower()
df_limpio['campus'] = df_limpio['campus'].replace({
    'slp cntro': 'slp centro',
    'slp centro ': 'slp centro'
})

df_limpio['modalidad'] = df_limpio['modalidad'].str.strip().str.lower()
df_limpio['modalidad'] = df_limpio['modalidad'].replace({'escolar': 'escolarizada'})

# 2. Eliminar duplicados
df_limpio = df_limpio.drop_duplicates(subset='id_estudiante', keep='first')

# 3. Corregir rangos (0–100) en promedio y asistencia
df_limpio['promedio'] = df_limpio['promedio'].clip(0, 100)
df_limpio['asistencia_pct'] = df_limpio['asistencia_pct'].clip(0, 100)

# 4. Corregir creditos_aprobados
df_limpio['creditos_aprobados'] = np.minimum(df_limpio['creditos_aprobados'], df_limpio['creditos_inscritos'])

# 5. Imputar faltantes
for col in ['edad', 'promedio', 'asistencia_pct']:
    df_limpio[col] = df_limpio[col].fillna(df_limpio[col].median())

In [ ]:
#C2
display(df_limpio.head())

   id_estudiante nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0            201  Laura  19.0  slp centro  escolarizada      87.0            93.0                  30                  29
1            202   Iván  20.0  slp centro  escolarizada      92.0            86.0                  32                  31
2            203  María  20.5   slp norte         mixta      75.0            80.0                  28                  27
3            204  Diego  22.0  slp centro         mixta      85.0            88.0                  30                  29
4            205  Sofía  21.0   matehuala  escolarizada      83.0            87.0                  26                  25

In [ ]:
print("Nulos por columna:\n", df_limpio.isnull().sum())

# Verificamos valores únicos de campus para asegurar normalización
print("\nCampus normalizados:", df_limpio['campus'].unique())

# Verificamos que los créditos aprobados no superen a los inscritos
errores_logicos = (df_limpio['creditos_aprobados'] > df_limpio['creditos_inscritos']).sum()
print(f"\nErrores de lógica en créditos: {errores_logicos}")

Nulos por columna:
 id_estudiante         0
nombre                0
edad                  0
campus                0
modalidad             0
promedio              0
asistencia_pct        0
creditos_inscritos    0
creditos_aprobados    0
dtype: int64

Campus normalizados: ['SLP Centro' 'SLP Norte' 'Matehuala']

Errores de lógica en créditos: 0

actividad d

In [ ]:
# d1
bajos_promedios = df_limpio[df_limpio['promedio'] < 80]
escolarizada_centro = df_limpio[(df_limpio['campus'] == 'slp centro') & (df_limpio['modalidad'] == 'escolarizada')]

print(f"Estudiantes con promedio < 80: {len(bajos_promedios)}")
print(f"Estudiantes en SLP Centro / Escolarizada: {len(escolarizada_centro)}")

Estudiantes con promedio < 80: 4
Estudiantes en SLP Centro / Escolarizada: 4

In [ ]:
#d2
df_limpio['tasa_aprobacion'] = df_limpio['creditos_aprobados'] / df_limpio['creditos_inscritos']

#condiciones
condiciones = [
    (df_limpio['promedio'] < 70) | (df_limpio['asistencia_pct'] < 75),
    (df_limpio['promedio'] < 80)
]
opciones = ['Alto', 'Medio']

df_limpio['riesgo_academico'] = np.select(condiciones, opciones, default='Bajo')

actividad e

In [ ]:
# e1
df_final = pd.merge(df_limpio, apoyos, on='id_estudiante', how='left', indicator=True)

In [ ]:
# e2
print("--- Shape final ---")
print(df_final.shape)

print("\n--- Conteo de cruce (Merge) ---")
print(df_final['_merge'].value_counts())

print("\n--- Promedio por Campus ---")
print(df_final.groupby('campus')['promedio'].mean())

print("\n--- Distribución de Riesgo Académico ---")
print(df_final['riesgo_academico'].value_counts())

--- Shape final ---
(11, 14)

--- Conteo de cruce (Merge) ---
_merge
both          6
left_only     5
right_only    0
Name: count, dtype: int64

--- Promedio por Campus ---
campus
matehuala     75.500000
slp centro    83.666667
slp norte     90.000000
Name: promedio, dtype: float64

--- Distribución de Riesgo Académico ---
riesgo_academico
Bajo     7
Medio    3
Alto     1
Name: count, dtype: int64

In [ ]:
# e3
import os
os.makedirs("salida_eval", exist_ok=True)
df_final.to_csv("salida_eval/estudiantes_preprocesados_eval.csv", index=False)
print("Archivo guardado con éxito en 'salida_eval/'")

Archivo guardado con éxito en 'salida_eval/'

In [ ]:
df_limpio = df.copy()

# 9.1 Quitar espacios
df_limpio["campus"] = df_limpio["campus"].astype(str).str.strip()
df_limpio["modalidad"] = df_limpio["modalidad"].astype(str).str.strip()

# 9.2 Normalizar y corregir etiquetas
df_limpio["campus"] = df_limpio["campus"].str.lower().map({
    "slp centro": "SLP Centro",
    "slp cntro": "SLP Centro",
    "slp norte": "SLP Norte",
    "matehuala": "Matehuala"
}).fillna(df_limpio["campus"])

df_limpio["modalidad"] = df_limpio["modalidad"].str.lower().map({
    "escolarizada": "Escolarizada",
    "escolar": "Escolarizada",
    "mixta": "Mixta"
}).fillna(df_limpio["modalidad"])

# 9.3 Eliminar duplicados por id
df_limpio = df_limpio.drop_duplicates(subset=["id_estudiante"], keep="first").copy()

# 9.4 Corregir rangos
df_limpio["promedio"] = df_limpio["promedio"].clip(0, 100)
df_limpio["asistencia_pct"] = df_limpio["asistencia_pct"].clip(0, 100)

# 9.5 Corregir error lógico
df_limpio["creditos_aprobados"] = np.minimum(df_limpio["creditos_aprobados"], df_limpio["creditos_inscritos"])

# 9.6 Imputación simple con mediana
for col in ["edad", "promedio", "asistencia_pct"]:
    df_limpio[col] = df_limpio[col].fillna(df_limpio[col].median())

print("Limpieza completada ✅")
display(df_limpio)

Limpieza completada ✅

    id_estudiante  nombre  edad      campus     modalidad  promedio  asistencia_pct  creditos_inscritos  creditos_aprobados
0             201   Laura  19.0  SLP Centro  Escolarizada      87.0            93.0                  30                  29
1             202    Iván  20.0  SLP Centro  Escolarizada      92.0            86.0                  32                  31
2             203   María  20.5   SLP Norte         Mixta      75.0            80.0                  28                  27
3             204   Diego  22.0  SLP Centro         Mixta      85.0            88.0                  30                  29
4             205   Sofía  21.0   Matehuala  Escolarizada      83.0            87.0                  26                  25
5             206    Raúl  19.0   SLP Norte         Mixta     100.0            91.0                  30                  30
6             207  Carmen  20.0   Matehuala         Mixta      68.0            74.0                  24                  22
7             208    Joel  23.0  SLP Centro  Escolarizada      71.0            77.0                  30                  28
8             209   Paola  21.0   SLP Norte  Escolarizada      95.0            98.0                  32                  31
9             210  Andrés  20.0  SLP Centro  Escolarizada      79.0           100.0                  28                  28
10            211   Karla  22.0  SLP Centro         Mixta      88.0            85.0                  30                  30

In [ ]:
# Verificación después de limpiar
reporte = pd.DataFrame({
    "criterio": [
        "faltantes_totales",
        "duplicados_por_id",
        "campus_invalidos",
        "modalidad_invalidos",
        "promedio_fuera_rango",
        "asistencia_fuera_rango",
        "error_logico_creditos"
    ],
    "valor": [
        int(df_limpio.isna().sum().sum()),
        int(df_limpio.duplicated(subset=["id_estudiante"]).sum()),
        int((~df_limpio["campus"].isin(["SLP Centro", "SLP Norte", "Matehuala"])).sum()),
        int((~df_limpio["modalidad"].isin(["Escolarizada", "Mixta"])).sum()),
        int((~df_limpio["promedio"].between(0, 100, inclusive="both")).sum()),
        int((~df_limpio["asistencia_pct"].between(0, 100, inclusive="both")).sum()),
        int((df_limpio["creditos_aprobados"] > df_limpio["creditos_inscritos"]).sum()),
    ]
})
reporte

                 criterio  valor
0       faltantes_totales      0
1       duplicados_por_id      0
2        campus_invalidos      0
3     modalidad_invalidos      0
4    promedio_fuera_rango      0
5  asistencia_fuera_rango      0
6   error_logico_creditos      0